In [1]:
import pandas as pd
df=pd.read_csv('centertraining.csv')
print(df.head())
df2=df

   Unnamed: 0  Unnamed: 1      Time   Value  Length  Width  Flow Rate  Weight  \
0           0          10  1/1/2020  147.66    3.91   1.05      50.00    1.17
1           1          10  1/2/2020   83.03    2.76   0.96      24.91    0.83
2           2          10  1/3/2020   69.80    1.35   3.07       5.94    0.40
3           3          10  1/4/2020   56.52    1.83   1.23      10.96    0.55
4           4          10  1/5/2020   76.90     NaN   0.49       2.37    0.26

   Height
0    0.09
1    0.29
2    0.92
3    0.37
4    0.15

In [2]:
df=df.loc[:,~df.columns.str.contains('^Unnamed')]

In [3]:
df['Time']

0      1/1/2020
1      1/2/2020
2      1/3/2020
3      1/4/2020
4      1/5/2020
5      1/6/2020
6      1/7/2020
7      1/8/2020
8      1/9/2020
9     1/10/2020
10    1/11/2020
11    1/12/2020
12    1/13/2020
13    1/14/2020
14    1/15/2020
15    1/16/2020
16    1/17/2020
17    1/18/2020
18    1/19/2020
19    1/20/2020
20    1/21/2020
21    1/22/2020
22    1/23/2020
23    1/24/2020
24    1/25/2020
25    1/26/2020
26    1/27/2020
27    1/28/2020
28    1/29/2020
29    1/30/2020
30    1/30/2020
31    1/31/2020
Name: Time, dtype: object

In [7]:
df[df['Time'].between('1/10/2020','1/13/2020')]
#df['Time'].between('1/10/2020','1/13/2020')

         Time   Value  Length  Width  Flow Rate  Weight  Height
9   1/10/2020   99.12    5.41  10.31      95.74    1.62    3.09
10  1/11/2020  100.25    3.70   5.15      44.78    1.11    1.55
11  1/12/2020  158.33    3.81   2.58      47.50    1.14    0.77
12  1/13/2020   78.88    2.69   1.12      23.66    0.81    0.34

In [5]:
df[df['Time'].between('2020/1/10','2020/1/13')]

Empty DataFrame
Columns: [Time, Value, Length, Width, Flow Rate, Weight, Height]
Index: []

In [8]:
import numpy as np
sampling = np.random.permutation(31)
df.take(sampling)
df.sample(n=5)

         Time   Value  Length  Width  Flow Rate  Weight  Height
22  1/23/2020     NaN    3.72   0.08      45.13    1.11    0.02
0    1/1/2020  147.66    3.91   1.05      50.00    1.17    0.09
29  1/30/2020  105.27    4.03   4.69      53.18    1.21    1.41
6    1/7/2020   67.15    2.48   5.03      20.15    0.74    1.51
3    1/4/2020   56.52    1.83   1.23      10.96    0.55    0.37

In [9]:
bins=[0,80,150,200]
data_inbins=pd.cut(df['Value'],bins)
pd.value_counts(data_inbins)

Value
(0, 80]       18
(80, 150]     10
(150, 200]     2
Name: count, dtype: int64

In [8]:
data_autobins=pd.qcut(df['Value'],3)
pd.value_counts(data_autobins)

(90.953, 196.43]               10
(69.47, 90.953]                10
(7.5089999999999995, 69.47]    10
Name: Value, dtype: int64

In [9]:
df.replace(147.66, 1111)

         Time    Value  Length  Width  Flow Rate  Weight  Height
0    1/1/2020  1111.00    3.91   1.05      50.00    1.17    0.09
1    1/2/2020    83.03    2.76   0.96      24.91    0.83    0.29
2    1/3/2020    69.80    1.35   3.07       5.94    0.40    0.92
3    1/4/2020    56.52    1.83   1.23      10.96    0.55    0.37
4    1/5/2020    76.90     NaN   0.49       2.37    0.26    0.15
5    1/6/2020    78.53    2.69   1.57      23.56    0.81    0.47
6    1/7/2020    67.15    2.48   5.03      20.15    0.74    1.51
7    1/8/2020   196.43    4.25   1.01      58.93    1.27    0.30
8    1/9/2020    64.47    2.43   3.22      19.34    0.73    0.97
9   1/10/2020    99.12    5.41  10.31      95.74    1.62    3.09
10  1/11/2020   100.25    3.70   5.15      44.78    1.11    1.55
11  1/12/2020   158.33    3.81   2.58      47.50    1.14    0.77
12  1/13/2020    78.88    2.69   1.12      23.66    0.81    0.34
13  1/14/2020    68.81    1.31   3.59       5.64    0.39    1.08
14  1/15/2020    34.70    1.79   0.90      10.41    0.54    0.27
15  1/16/2020     7.51    0.83   2.87       2.25    0.25    0.47
16  1/17/2020    74.61    2.62   9.18      22.38    0.79    2.75
17  1/18/2020    63.80    2.42   9.18      19.14    0.73    2.29
18  1/19/2020   135.60    4.14   1.53      55.98    1.24    0.46
19  1/20/2020    61.25    2.37   4.90      18.37     NaN    1.47
20  1/21/2020   130.17    5.28   1.22      90.95    1.58    0.37
21  1/22/2020   141.79    3.61   0.31      42.54    1.08    0.09
22  1/23/2020      NaN    3.72   0.08      45.13    1.11    0.02
23  1/24/2020    74.94    2.62   0.10      22.48    0.79    0.03
24  1/25/2020    86.87    1.28   0.13       5.36    0.38    0.04
25  1/26/2020    32.96    1.74   0.17       9.89    0.52    0.05
26  1/27/2020    70.88    0.81   0.22       2.14    0.24    0.07
27  1/28/2020    70.88    2.55   3.28      21.26    0.77    0.98
28  1/29/2020    60.61    2.36   4.26      18.18    0.71    1.28
29  1/30/2020   105.27    4.03   4.69      53.18    1.21    1.41
30  1/30/2020   105.27    4.03   4.69      53.18    1.21    1.41
31  1/31/2020      NaN     NaN    NaN        NaN     NaN     NaN

In [11]:
df1=pd.read_csv('df1.csv')
print(df1)

   A  C
0  1  4
1  2  5
2  3  6

In [13]:
df1=df1.rename(columns={'A': 'a', 'C': 'c'}) 
df1=df1.rename(index={0: 'x', 1: 'y', 2: 'z'})
print(df1)

   a  c
x  1  4
y  2  5
z  3  6

In [15]:
df.isnull()

     Time  Value  Length  Width  Flow Rate  Weight  Height
0   False  False   False  False      False   False   False
1   False  False   False  False      False   False   False
2   False  False   False  False      False   False   False
3   False  False   False  False      False   False   False
4   False  False    True  False      False   False   False
5   False  False   False  False      False   False   False
6   False  False   False  False      False   False   False
7   False  False   False  False      False   False   False
8   False  False   False  False      False   False   False
9   False  False   False  False      False   False   False
10  False  False   False  False      False   False   False
11  False  False   False  False      False   False   False
12  False  False   False  False      False   False   False
13  False  False   False  False      False   False   False
14  False  False   False  False      False   False   False
15  False  False   False  False      False   False   False
16  False  False   False  False      False   False   False
17  False  False   False  False      False   False   False
18  False  False   False  False      False   False   False
19  False  False   False  False      False    True   False
20  False  False   False  False      False   False   False
21  False  False   False  False      False   False   False
22  False   True   False  False      False   False   False
23  False  False   False  False      False   False   False
24  False  False   False  False      False   False   False
25  False  False   False  False      False   False   False
26  False  False   False  False      False   False   False
27  False  False   False  False      False   False   False
28  False  False   False  False      False   False   False
29  False  False   False  False      False   False   False
30  False  False   False  False      False   False   False
31  False   True    True   True       True    True    True

In [16]:
df[df.isnull().any(axis=1)]

         Time  Value  Length  Width  Flow Rate  Weight  Height
4    1/5/2020  76.90     NaN   0.49       2.37    0.26    0.15
19  1/20/2020  61.25    2.37   4.90      18.37     NaN    1.47
22  1/23/2020    NaN    3.72   0.08      45.13    1.11    0.02
31  1/31/2020    NaN     NaN    NaN        NaN     NaN     NaN

In [17]:
df[df['Value'].isnull()]

         Time  Value  Length  Width  Flow Rate  Weight  Height
22  1/23/2020    NaN    3.72   0.08      45.13    1.11    0.02
31  1/31/2020    NaN     NaN    NaN        NaN     NaN     NaN

In [18]:
df[df['Length'].isnull()]

         Time  Value  Length  Width  Flow Rate  Weight  Height
4    1/5/2020   76.9     NaN   0.49       2.37    0.26    0.15
31  1/31/2020    NaN     NaN    NaN        NaN     NaN     NaN

In [19]:
df[df['Flow Rate'].isnull()]

         Time  Value  Length  Width  Flow Rate  Weight  Height
31  1/31/2020    NaN     NaN    NaN        NaN     NaN     NaN

In [20]:
df.dropna()

         Time   Value  Length  Width  Flow Rate  Weight  Height
0    1/1/2020  147.66    3.91   1.05      50.00    1.17    0.09
1    1/2/2020   83.03    2.76   0.96      24.91    0.83    0.29
2    1/3/2020   69.80    1.35   3.07       5.94    0.40    0.92
3    1/4/2020   56.52    1.83   1.23      10.96    0.55    0.37
5    1/6/2020   78.53    2.69   1.57      23.56    0.81    0.47
6    1/7/2020   67.15    2.48   5.03      20.15    0.74    1.51
7    1/8/2020  196.43    4.25   1.01      58.93    1.27    0.30
8    1/9/2020   64.47    2.43   3.22      19.34    0.73    0.97
9   1/10/2020   99.12    5.41  10.31      95.74    1.62    3.09
10  1/11/2020  100.25    3.70   5.15      44.78    1.11    1.55
11  1/12/2020  158.33    3.81   2.58      47.50    1.14    0.77
12  1/13/2020   78.88    2.69   1.12      23.66    0.81    0.34
13  1/14/2020   68.81    1.31   3.59       5.64    0.39    1.08
14  1/15/2020   34.70    1.79   0.90      10.41    0.54    0.27
15  1/16/2020    7.51    0.83   2.87       2.25    0.25    0.47
16  1/17/2020   74.61    2.62   9.18      22.38    0.79    2.75
17  1/18/2020   63.80    2.42   9.18      19.14    0.73    2.29
18  1/19/2020  135.60    4.14   1.53      55.98    1.24    0.46
20  1/21/2020  130.17    5.28   1.22      90.95    1.58    0.37
21  1/22/2020  141.79    3.61   0.31      42.54    1.08    0.09
23  1/24/2020   74.94    2.62   0.10      22.48    0.79    0.03
24  1/25/2020   86.87    1.28   0.13       5.36    0.38    0.04
25  1/26/2020   32.96    1.74   0.17       9.89    0.52    0.05
26  1/27/2020   70.88    0.81   0.22       2.14    0.24    0.07
27  1/28/2020   70.88    2.55   3.28      21.26    0.77    0.98
28  1/29/2020   60.61    2.36   4.26      18.18    0.71    1.28
29  1/30/2020  105.27    4.03   4.69      53.18    1.21    1.41
30  1/30/2020  105.27    4.03   4.69      53.18    1.21    1.41

In [21]:
df=df2
df.fillna(0)

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.66,3.91,1.05,50.00,1.17,0.09
1,1,10,1/2/2020,83.03,2.76,0.96,24.91,0.83,0.29
2,2,10,1/3/2020,69.80,1.35,3.07,5.94,0.40,0.92
3,3,10,1/4/2020,56.52,1.83,1.23,10.96,0.55,0.37
4,4,10,1/5/2020,76.90,0.00,0.49,2.37,0.26,0.15
5,5,10,1/6/2020,78.53,2.69,1.57,23.56,0.81,0.47
6,6,10,1/7/2020,67.15,2.48,5.03,20.15,0.74,1.51
7,7,10,1/8/2020,196.43,4.25,1.01,58.93,1.27,0.30
8,8,10,1/9/2020,64.47,2.43,3.22,19.34,0.73,0.97
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
10,10,10,1/11/2020,100.25,3.70,5.15,44.78,1.11,1.55
11,11,10,1/12/2020,158.33,3.81,2.58,47.50,1.14,0.77
12,12,10,1/13/2020,78.88,2.69,1.12,23.66,0.81,0.34
13,13,10,1/14/2020,68.81,1.31,3.59,5.64,0.39,1.08
14,14,10,1/15/2020,34.70,1.79,0.90,10.41,0.54,0.27
15,15,10,1/16/2020,7.51,0.83,2.87,2.25,0.25,0.47
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29
18,18,10,1/19/2020,135.60,4.14,1.53,55.98,1.24,0.46
19,19,10,1/20/2020,61.25,2.37,4.90,18.37,0.00,1.47
20,20,10,1/21/2020,130.17,5.28,1.22,90.95,1.58,0.37
21,21,10,1/22/2020,141.79,3.61,0.31,42.54,1.08,0.09
22,22,10,1/23/2020,0.00,3.72,0.08,45.13,1.11,0.02
23,23,10,1/24/2020,74.94,2.62,0.10,22.48,0.79,0.03
24,24,10,1/25/2020,86.87,1.28,0.13,5.36,0.38,0.04
25,25,10,1/26/2020,32.96,1.74,0.17,9.89,0.52,0.05
26,26,10,1/27/2020,70.88,0.81,0.22,2.14,0.24,0.07
27,27,10,1/28/2020,70.88,2.55,3.28,21.26,0.77,0.98
28,28,10,1/29/2020,60.61,2.36,4.26,18.18,0.71,1.28
29,29,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
30,30,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
31,31,10,1/31/2020,0.00,0.00,0.00,0.00,0.00,0.00

In [22]:
df=df2
df.fillna({'Value':1000,'Length':2000})

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.66,3.91,1.05,50.00,1.17,0.09
1,1,10,1/2/2020,83.03,2.76,0.96,24.91,0.83,0.29
2,2,10,1/3/2020,69.80,1.35,3.07,5.94,0.40,0.92
3,3,10,1/4/2020,56.52,1.83,1.23,10.96,0.55,0.37
4,4,10,1/5/2020,76.90,2000.00,0.49,2.37,0.26,0.15
5,5,10,1/6/2020,78.53,2.69,1.57,23.56,0.81,0.47
6,6,10,1/7/2020,67.15,2.48,5.03,20.15,0.74,1.51
7,7,10,1/8/2020,196.43,4.25,1.01,58.93,1.27,0.30
8,8,10,1/9/2020,64.47,2.43,3.22,19.34,0.73,0.97
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
10,10,10,1/11/2020,100.25,3.70,5.15,44.78,1.11,1.55
11,11,10,1/12/2020,158.33,3.81,2.58,47.50,1.14,0.77
12,12,10,1/13/2020,78.88,2.69,1.12,23.66,0.81,0.34
13,13,10,1/14/2020,68.81,1.31,3.59,5.64,0.39,1.08
14,14,10,1/15/2020,34.70,1.79,0.90,10.41,0.54,0.27
15,15,10,1/16/2020,7.51,0.83,2.87,2.25,0.25,0.47
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29
18,18,10,1/19/2020,135.60,4.14,1.53,55.98,1.24,0.46
19,19,10,1/20/2020,61.25,2.37,4.90,18.37,NaN,1.47
20,20,10,1/21/2020,130.17,5.28,1.22,90.95,1.58,0.37
21,21,10,1/22/2020,141.79,3.61,0.31,42.54,1.08,0.09
22,22,10,1/23/2020,1000.00,3.72,0.08,45.13,1.11,0.02
23,23,10,1/24/2020,74.94,2.62,0.10,22.48,0.79,0.03
24,24,10,1/25/2020,86.87,1.28,0.13,5.36,0.38,0.04
25,25,10,1/26/2020,32.96,1.74,0.17,9.89,0.52,0.05
26,26,10,1/27/2020,70.88,0.81,0.22,2.14,0.24,0.07
27,27,10,1/28/2020,70.88,2.55,3.28,21.26,0.77,0.98
28,28,10,1/29/2020,60.61,2.36,4.26,18.18,0.71,1.28
29,29,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
30,30,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
31,31,10,1/31/2020,1000.00,2000.00,NaN,NaN,NaN,NaN

In [23]:
df=df2
df.fillna(method='ffill')

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.66,3.91,1.05,50.00,1.17,0.09
1,1,10,1/2/2020,83.03,2.76,0.96,24.91,0.83,0.29
2,2,10,1/3/2020,69.80,1.35,3.07,5.94,0.40,0.92
3,3,10,1/4/2020,56.52,1.83,1.23,10.96,0.55,0.37
4,4,10,1/5/2020,76.90,1.83,0.49,2.37,0.26,0.15
5,5,10,1/6/2020,78.53,2.69,1.57,23.56,0.81,0.47
6,6,10,1/7/2020,67.15,2.48,5.03,20.15,0.74,1.51
7,7,10,1/8/2020,196.43,4.25,1.01,58.93,1.27,0.30
8,8,10,1/9/2020,64.47,2.43,3.22,19.34,0.73,0.97
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
10,10,10,1/11/2020,100.25,3.70,5.15,44.78,1.11,1.55
11,11,10,1/12/2020,158.33,3.81,2.58,47.50,1.14,0.77
12,12,10,1/13/2020,78.88,2.69,1.12,23.66,0.81,0.34
13,13,10,1/14/2020,68.81,1.31,3.59,5.64,0.39,1.08
14,14,10,1/15/2020,34.70,1.79,0.90,10.41,0.54,0.27
15,15,10,1/16/2020,7.51,0.83,2.87,2.25,0.25,0.47
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29
18,18,10,1/19/2020,135.60,4.14,1.53,55.98,1.24,0.46
19,19,10,1/20/2020,61.25,2.37,4.90,18.37,1.24,1.47
20,20,10,1/21/2020,130.17,5.28,1.22,90.95,1.58,0.37
21,21,10,1/22/2020,141.79,3.61,0.31,42.54,1.08,0.09
22,22,10,1/23/2020,141.79,3.72,0.08,45.13,1.11,0.02
23,23,10,1/24/2020,74.94,2.62,0.10,22.48,0.79,0.03
24,24,10,1/25/2020,86.87,1.28,0.13,5.36,0.38,0.04
25,25,10,1/26/2020,32.96,1.74,0.17,9.89,0.52,0.05
26,26,10,1/27/2020,70.88,0.81,0.22,2.14,0.24,0.07
27,27,10,1/28/2020,70.88,2.55,3.28,21.26,0.77,0.98
28,28,10,1/29/2020,60.61,2.36,4.26,18.18,0.71,1.28
29,29,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
30,30,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
31,31,10,1/31/2020,105.27,4.03,4.69,53.18,1.21,1.41

In [24]:
df=df2
df.fillna(df.mean())

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.660000,3.910000,1.050000,50.000000,1.170000,0.090000
1,1,10,1/2/2020,83.030000,2.760000,0.960000,24.910000,0.830000,0.290000
2,2,10,1/3/2020,69.800000,1.350000,3.070000,5.940000,0.400000,0.920000
3,3,10,1/4/2020,56.520000,1.830000,1.230000,10.960000,0.550000,0.370000
4,4,10,1/5/2020,76.900000,2.827333,0.490000,2.370000,0.260000,0.150000
5,5,10,1/6/2020,78.530000,2.690000,1.570000,23.560000,0.810000,0.470000
6,6,10,1/7/2020,67.150000,2.480000,5.030000,20.150000,0.740000,1.510000
7,7,10,1/8/2020,196.430000,4.250000,1.010000,58.930000,1.270000,0.300000
8,8,10,1/9/2020,64.470000,2.430000,3.220000,19.340000,0.730000,0.970000
9,9,10,1/10/2020,99.120000,5.410000,10.310000,95.740000,1.620000,3.090000
10,10,10,1/11/2020,100.250000,3.700000,5.150000,44.780000,1.110000,1.550000
11,11,10,1/12/2020,158.330000,3.810000,2.580000,47.500000,1.140000,0.770000
12,12,10,1/13/2020,78.880000,2.690000,1.120000,23.660000,0.810000,0.340000
13,13,10,1/14/2020,68.810000,1.310000,3.590000,5.640000,0.390000,1.080000
14,14,10,1/15/2020,34.700000,1.790000,0.900000,10.410000,0.540000,0.270000
15,15,10,1/16/2020,7.510000,0.830000,2.870000,2.250000,0.250000,0.470000
16,16,10,1/17/2020,74.610000,2.620000,9.180000,22.380000,0.790000,2.750000
17,17,10,1/18/2020,63.800000,2.420000,9.180000,19.140000,0.730000,2.290000
18,18,10,1/19/2020,135.600000,4.140000,1.530000,55.980000,1.240000,0.460000
19,19,10,1/20/2020,61.250000,2.370000,4.900000,18.370000,0.832667,1.470000
20,20,10,1/21/2020,130.170000,5.280000,1.220000,90.950000,1.580000,0.370000
21,21,10,1/22/2020,141.790000,3.610000,0.310000,42.540000,1.080000,0.090000
22,22,10,1/23/2020,86.766333,3.720000,0.080000,45.130000,1.110000,0.020000
23,23,10,1/24/2020,74.940000,2.620000,0.100000,22.480000,0.790000,0.030000
24,24,10,1/25/2020,86.870000,1.280000,0.130000,5.360000,0.380000,0.040000
25,25,10,1/26/2020,32.960000,1.740000,0.170000,9.890000,0.520000,0.050000
26,26,10,1/27/2020,70.880000,0.810000,0.220000,2.140000,0.240000,0.070000
27,27,10,1/28/2020,70.880000,2.550000,3.280000,21.260000,0.770000,0.980000
28,28,10,1/29/2020,60.610000,2.360000,4.260000,18.180000,0.710000,1.280000
29,29,10,1/30/2020,105.270000,4.030000,4.690000,53.180000,1.210000,1.410000
30,30,10,1/30/2020,105.270000,4.030000,4.690000,53.180000,1.210000,1.410000
31,31,10,1/31/2020,86.766333,2.827333,2.841613,29.880645,0.832667,0.818065

In [25]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [27]:
df.drop_duplicates()

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.66,3.91,1.05,50.00,1.17,0.09
1,1,10,1/2/2020,83.03,2.76,0.96,24.91,0.83,0.29
2,2,10,1/3/2020,69.80,1.35,3.07,5.94,0.40,0.92
3,3,10,1/4/2020,56.52,1.83,1.23,10.96,0.55,0.37
4,4,10,1/5/2020,76.90,NaN,0.49,2.37,0.26,0.15
5,5,10,1/6/2020,78.53,2.69,1.57,23.56,0.81,0.47
6,6,10,1/7/2020,67.15,2.48,5.03,20.15,0.74,1.51
7,7,10,1/8/2020,196.43,4.25,1.01,58.93,1.27,0.30
8,8,10,1/9/2020,64.47,2.43,3.22,19.34,0.73,0.97
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
10,10,10,1/11/2020,100.25,3.70,5.15,44.78,1.11,1.55
11,11,10,1/12/2020,158.33,3.81,2.58,47.50,1.14,0.77
12,12,10,1/13/2020,78.88,2.69,1.12,23.66,0.81,0.34
13,13,10,1/14/2020,68.81,1.31,3.59,5.64,0.39,1.08
14,14,10,1/15/2020,34.70,1.79,0.90,10.41,0.54,0.27
15,15,10,1/16/2020,7.51,0.83,2.87,2.25,0.25,0.47
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29
18,18,10,1/19/2020,135.60,4.14,1.53,55.98,1.24,0.46
19,19,10,1/20/2020,61.25,2.37,4.90,18.37,NaN,1.47
20,20,10,1/21/2020,130.17,5.28,1.22,90.95,1.58,0.37
21,21,10,1/22/2020,141.79,3.61,0.31,42.54,1.08,0.09
22,22,10,1/23/2020,NaN,3.72,0.08,45.13,1.11,0.02
23,23,10,1/24/2020,74.94,2.62,0.10,22.48,0.79,0.03
24,24,10,1/25/2020,86.87,1.28,0.13,5.36,0.38,0.04
25,25,10,1/26/2020,32.96,1.74,0.17,9.89,0.52,0.05
26,26,10,1/27/2020,70.88,0.81,0.22,2.14,0.24,0.07
27,27,10,1/28/2020,70.88,2.55,3.28,21.26,0.77,0.98
28,28,10,1/29/2020,60.61,2.36,4.26,18.18,0.71,1.28
29,29,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
30,30,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
31,31,10,1/31/2020,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
dd=df.describe()
dd

,Unnamed: 0,Unnamed: 1,Value,Length,Width,Flow Rate,Weight,Height
count,32.000000,32.0,30.000000,30.000000,31.000000,31.000000,30.000000,31.000000
mean,15.500000,10.0,86.766333,2.827333,2.841613,29.880645,0.832667,0.818065
std,9.380832,0.0,39.983613,1.216306,2.793994,24.546239,0.379064,0.814708
min,0.000000,10.0,7.510000,0.810000,0.080000,2.140000,0.240000,0.020000
25%,7.750000,10.0,65.140000,1.962500,0.930000,10.685000,0.542500,0.210000
50%,15.500000,10.0,75.920000,2.620000,1.570000,22.380000,0.790000,0.470000
75%,23.250000,10.0,104.015000,3.787500,4.475000,46.315000,1.132500,1.345000
max,31.000000,10.0,196.430000,5.410000,10.310000,95.740000,1.620000,3.090000

In [29]:
df['Width'].describe()

count    31.000000
mean      2.841613
std       2.793994
min       0.080000
25%       0.930000
50%       1.570000
75%       4.475000
max      10.310000
Name: Width, dtype: float64

In [30]:
df[df['Width']>2.841613]

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
2,2,10,1/3/2020,69.80,1.35,3.07,5.94,0.40,0.92
6,6,10,1/7/2020,67.15,2.48,5.03,20.15,0.74,1.51
8,8,10,1/9/2020,64.47,2.43,3.22,19.34,0.73,0.97
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
10,10,10,1/11/2020,100.25,3.70,5.15,44.78,1.11,1.55
13,13,10,1/14/2020,68.81,1.31,3.59,5.64,0.39,1.08
15,15,10,1/16/2020,7.51,0.83,2.87,2.25,0.25,0.47
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29
19,19,10,1/20/2020,61.25,2.37,4.90,18.37,NaN,1.47
27,27,10,1/28/2020,70.88,2.55,3.28,21.26,0.77,0.98
28,28,10,1/29/2020,60.61,2.36,4.26,18.18,0.71,1.28
29,29,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41
30,30,10,1/30/2020,105.27,4.03,4.69,53.18,1.21,1.41

In [31]:
df[df['Width']>2.841613+2.793994*2]

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
9,9,10,1/10/2020,99.12,5.41,10.31,95.74,1.62,3.09
16,16,10,1/17/2020,74.61,2.62,9.18,22.38,0.79,2.75
17,17,10,1/18/2020,63.80,2.42,9.18,19.14,0.73,2.29

In [32]:
len(df[df['Width']>2.841613+2.793994*2])

3

In [33]:
df[df['Width']<=2.841613]

,Unnamed: 0,Unnamed: 1,Time,Value,Length,Width,Flow Rate,Weight,Height
0,0,10,1/1/2020,147.66,3.91,1.05,50.00,1.17,0.09
1,1,10,1/2/2020,83.03,2.76,0.96,24.91,0.83,0.29
3,3,10,1/4/2020,56.52,1.83,1.23,10.96,0.55,0.37
4,4,10,1/5/2020,76.90,NaN,0.49,2.37,0.26,0.15
5,5,10,1/6/2020,78.53,2.69,1.57,23.56,0.81,0.47
7,7,10,1/8/2020,196.43,4.25,1.01,58.93,1.27,0.30
11,11,10,1/12/2020,158.33,3.81,2.58,47.50,1.14,0.77
12,12,10,1/13/2020,78.88,2.69,1.12,23.66,0.81,0.34
14,14,10,1/15/2020,34.70,1.79,0.90,10.41,0.54,0.27
18,18,10,1/19/2020,135.60,4.14,1.53,55.98,1.24,0.46
20,20,10,1/21/2020,130.17,5.28,1.22,90.95,1.58,0.37
21,21,10,1/22/2020,141.79,3.61,0.31,42.54,1.08,0.09
22,22,10,1/23/2020,NaN,3.72,0.08,45.13,1.11,0.02
23,23,10,1/24/2020,74.94,2.62,0.10,22.48,0.79,0.03
24,24,10,1/25/2020,86.87,1.28,0.13,5.36,0.38,0.04
25,25,10,1/26/2020,32.96,1.74,0.17,9.89,0.52,0.05
26,26,10,1/27/2020,70.88,0.81,0.22,2.14,0.24,0.07