In [2]:
import pandas as pd
df4=pd.read_csv('df4.csv')
df4

   a  b  c  d
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0

In [2]:
df5=pd.read_csv('df5.csv')
df5

   b  c  d  e
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

In [3]:
df4=df4.rename(index={0: 1, 1: 2, 2: 3})
df4

   a  b  c  d
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0

In [4]:
df5=df5.rename(index={0: 2, 1: 3, 2: 4})
df5

   b  c  d  e
2  1  1  1  1
3  1  1  1  1
4  1  1  1  1

In [5]:
pd.concat([df4,df5],axis=0,join='inner')

   b  c  d
1  0  0  0
2  0  0  0
3  0  0  0
2  1  1  1
3  1  1  1
4  1  1  1

In [6]:
pd.concat([df4,df5],axis=0,join='outer')

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

     a  b  c  d    e
1  0.0  0  0  0  NaN
2  0.0  0  0  0  NaN
3  0.0  0  0  0  NaN
2  NaN  1  1  1  1.0
3  NaN  1  1  1  1.0
4  NaN  1  1  1  1.0

In [7]:
dfConcat=pd.concat([df4,df5],axis=0,join='outer')
dfConcat.to_csv('dfConcat.csv',index=False)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

In [3]:
df6=pd.read_csv('df6.csv')
df6

   a  b  c  d
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2

In [4]:
df7=pd.read_csv('df7.csv')
df7

   b  c  d  e
0  3  3  3  3
1  3  3  3  3
2  3  3  3  3

In [5]:
df6=df6.rename(index={0: 1, 1: 2, 2: 3})
df6

   a  b  c  d
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2

In [6]:
df7=df7.rename(index={0: 2, 1: 3, 2: 4})
df7

   b  c  d  e
2  3  3  3  3
3  3  3  3  3
4  3  3  3  3

In [10]:
# don't use the "join_axes" parameter if pandas version is older than 1.0.0 
pd.concat([df6,df7],axis=1,join_axes=[df6.index])

   a  b  c  d    b    c    d    e
1  2  2  2  2  NaN  NaN  NaN  NaN
2  2  2  2  2  3.0  3.0  3.0  3.0
3  2  2  2  2  3.0  3.0  3.0  3.0

In [11]:
# use the following function if pandas version is newer than 1.0.0 
pd.merge(df6, df7, how='left', left_index=True, right_index=True)

   a  b_x  c_x  d_x  b_y  c_y  d_y    e
1  2    2    2    2  NaN  NaN  NaN  NaN
2  2    2    2    2  3.0  3.0  3.0  3.0
3  2    2    2    2  3.0  3.0  3.0  3.0

In [13]:
pd.concat([df6,df7],axis=1)

     a    b    c    d    b    c    d    e
1  2.0  2.0  2.0  2.0  NaN  NaN  NaN  NaN
2  2.0  2.0  2.0  2.0  3.0  3.0  3.0  3.0
3  2.0  2.0  2.0  2.0  3.0  3.0  3.0  3.0
4  NaN  NaN  NaN  NaN  3.0  3.0  3.0  3.0